# -*- coding: utf-8 -*-
"""01_load_data_py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X6h1be6Hw0ZWE-Y3N78ntFRwN_jXR29r
"""

import pandas as pd
import os

def load_imdb_data(file_path):
    """
    Checks the file path, loads the dataset, and prints basic information.
    """
    # 1. Check file path
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"ERROR: File not found at '{file_path}'! Please check the file name and path.")

    print(f"File found! Loading data from '{file_path}'...\n")

    # 2. Load the dataset
    df = pd.read_csv(file_path)

    # 3. Print basic dataset information
    print("-" * 40)
    print("BASIC DATASET INFORMATION")
    print("-" * 40)

    # Print shape
    print(f"Shape (Rows, Columns): {df.shape}\n")

    # Print sentiment distribution (Positive/Negative count)
    if 'sentiment' in df.columns:
        print("Sentiment Distribution:")
        print(df['sentiment'].value_counts().to_string())
        print("\n")
    else:
        print("WARNING: 'sentiment' column not found in the dataset.\n")

    # Print column types and null values
    print("Column Information (info):")
    df.info()
    print("\n")

    # Show the first few rows
    print("First 3 Rows of the Dataset:")
    print(df.head(3))
    print("-" * 40)

    return df

# For testing the script directly:
if __name__ == "__main__":
    file_path = 'IMDB Dataset.csv'
    df_raw = load_imdb_data(file_path)