# -*- coding: utf-8 -*-
"""02_preprocess_data_py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X6h1be6Hw0ZWE-Y3N78ntFRwN_jXR29r
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords, wordnet
from nltk import pos_tag
from collections import Counter
import warnings
warnings.filterwarnings('ignore')

# Downloading required NLTK packages
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

# Loading the dataset
df = pd.read_csv('IMDB Dataset.csv')
print("Original Dataset Size:", df.shape)

# Removing duplicate rows
df.drop_duplicates(inplace=True)
print("Dataset Size After Removing Duplicates:", df.shape)

# Defining the Lemmatizer
lemmatizer = WordNetLemmatizer()

# Preparing the stop-words list
stop_words = set(stopwords.words('english'))

negation_words = {
    # Core negations
    'not', 'no', 'nor', 'never', 'neither', 'nobody', 'nothing', 'nowhere', 'none',
    # Contractions
    'aren', "aren't", 'couldn', "couldn't", 'didn', "didn't",
    'doesn', "doesn't", 'hadn', "hadn't", 'hasn', "hasn't",
    'haven', "haven't", 'isn', "isn't", 'mightn', "mightn't",
    'mustn', "mustn't", 'needn', "needn't", 'shan', "shan't",
    'shouldn', "shouldn't", 'wasn', "wasn't", 'weren', "weren't",
    'won', "won't", 'wouldn', "wouldn't", 'ma',
    # Intensity adverbs
    'very', 'really', 'extremely', 'absolutely', 'completely',
    'totally', 'highly', 'deeply', 'incredibly', 'terribly',
    'barely', 'hardly', 'scarcely', 'slightly', 'somewhat',
    'rather', 'fairly', 'quite', 'almost', 'nearly',
    # Contrast conjunctions
    'but', 'however', 'although', 'though', 'despite', 'yet',
    'nevertheless', 'nonetheless', 'even', 'still', 'unless',
    'except', 'without', 'instead', 'whereas', 'while',
    # Degree words
    'too', 'only', 'just', 'few', 'less', 'least', 'against',
    'any', 'anyone', 'anything', 'whether'
}

# Removing negation words from the stop-words list
custom_stop_words = stop_words - negation_words

# ── Statistical feature functions (RAW DATA) ────────────────────

def get_word_count(text):
    text = re.sub(r'<.*?>', ' ', text)
    words = text.split()
    return len(words)

def get_avg_word_length(text):
    text = re.sub(r'<.*?>', ' ', text)
    words = re.findall(r'[a-zA-Z]+', text)
    return round(sum(len(w) for w in words) / len(words), 2) if words else 0

def get_exclamation_count(text):
    return text.count('!')

def get_all_caps_count(text):
    words = re.findall(r'[A-Z]{2,}', text)
    return len(words)

def get_lexical_diversity(text):
    text = re.sub(r'<.*?>', ' ', text)
    words = re.findall(r'[a-zA-Z]+', text.lower())
    return round(len(set(words)) / len(words), 4) if words else 0

# ── NEG_ function ────────────────────────────────────────────────

def apply_negation(tokens, negation_trigger_words, window=3):
    result = []
    negate = 0
    punctuation = {'.', ',', '!', '?', ';', ':'}

    for token in tokens:
        if token in punctuation:
            negate = 0
            result.append(token)
        elif token in negation_trigger_words:
            result.append(token)
            negate = window
        elif negate > 0:
            result.append(f'NEG_{token}')
            negate -= 1
        else:
            result.append(token)

    return result

# ── Main text cleaning function ──────────────────────────────────

def clean_text(text):
    # 1. Remove HTML tags
    text = re.sub(r'<.*?>', ' ', text)

    # 2. Convert to lowercase
    text = text.lower()

    # 3. Tokenize while preserving punctuation
    tokens = re.findall(r"[a-z']+|[.!?,;:]", text)

    # 4. Apply NEG_ tagging (BEFORE removing stop-words!)
    tokens = apply_negation(tokens, negation_words, window=3)

    # 5. Remove stop-words + Lemmatize
    cleaned = []
    for w in tokens:
        if w.startswith('NEG_'):
            root = w.replace('NEG_', '')
            if len(root) > 2:
                cleaned.append(f'NEG_{lemmatizer.lemmatize(root)}')
        elif w not in custom_stop_words and len(w) > 2 and w.isalpha():
            cleaned.append(lemmatizer.lemmatize(w))

    return ' '.join(cleaned)

# ── Apply statistical features to raw data ──────────────────────

print("Calculating statistical features...")

df['word_count']        = df['review'].apply(get_word_count)
df['avg_word_length']   = df['review'].apply(get_avg_word_length)
df['exclamation_count'] = df['review'].apply(get_exclamation_count)
df['all_caps_count']    = df['review'].apply(get_all_caps_count)
df['lexical_diversity'] = df['review'].apply(get_lexical_diversity)

print("✅ Statistical features calculated successfully!")

# ── Text cleaning process ────────────────────────────────────────

print("\nText cleaning and lemmatization process starting...")
print("Please wait (This may take approximately 1-3 minutes)...\n")

df['cleaned_review'] = df['review'].apply(clean_text)

print("✅ Text cleaning completed successfully!")

# ── Sentiment encoding: positive → 1, negative → 0 ──────────────

df['sentiment'] = df['sentiment'].map({'positive': 1, 'negative': 0})
print("✅ Sentiment encoding completed! (positive→1, negative→0)")

# ── Column ordering ──────────────────────────────────────────────

df = df[['review', 'cleaned_review', 'sentiment', 'word_count',
         'avg_word_length', 'lexical_diversity',
         'exclamation_count', 'all_caps_count']]

# ── Display results ──────────────────────────────────────────────

display(df.head(3))

# ── Save as CSV ──────────────────────────────────────────────────

df.to_csv('cleaned_data_set.csv', index=False)
print("\n✅ Dataset saved as 'cleaned_data_set.csv'!")